### ISSUE TITLE
the README "switches" between ecobee and bluetooth

### ISSUE THREAD

**Issue by mrose17** [vojtamolda/homebridge-ecobee3-sensors#1]
i contacted ecobee a few months ago about fixing their homekit implementation to show the sensors as seperate accessories, but they've yet to push an update. so, this plugin is a great idea.

however: the README file mentions bluetooth/arduino in a few places, which leads me to suspect that there was a cut-and-paste that wasn't entirely reviewed!

best,

/mtr

**Comment by vojtamolda** [comment]
Hello @mrose17,

Thanks for opening the first issue here. The readme isn't finished yet... I apologize for the typos and mistakes. I plan to fix it soon-ish. You know how it is with OS projects - documentation is the source code 😉

You're right, the first `readme.md` was indeed a copy & paste from my other [Homebridge plugin](/vojtamolda/homebridge-bluetooth/) so that's where bluetooth and arduino come from...

I tried contacting Ecobee too, but I'm not sure if this will ever happen. They would have to switch from a pure HomeKit accessory into a HomeKit bridge (like Phillips Hue & friends). Otherwise it's impossible to add the sensors, since the existing sensor hardware can't talk to Apple devices directly. The communication needs to be bridged by the thermostat.

Do you know if there is a thread or a discussion about the sensors not being visible in HomeKit somewhere? I'd like to make this plugin a bit more public and maybe get more people to use it. And who know maybe even contribute improvements... The `readme.md` file is horrible and could use some work... 😉

**Comment by mrose17** [comment]
thanks for the speedy reply. 

no worries on the typos/etc. ... it's a new project

it hadn't occurred to me that the issue may be hardware (if ecobee integrated the wrong MFi program). if so, that must be very painful.

in terms of making the plugin "more public", you've done the best thing which is to include the `homebridge-plugin` keyword. there is a slack community at https://homebridge-slackin.herokuapp.com/ (from the homebridge README file). that's where all of the conversations seem to be taking place.

**Comment by vojtamolda** [comment]
Thanks for the _Slack_ link. I'll go check it out.
