### ISSUE TITLE
Add .gitignore and .npmignore files

### ISSUE THREAD

**Issue by mrose17** [vojtamolda/homebridge-ecobee3-sensors#2]
...so other developers won't see `node_modules/*`files as changes!

**Comment by vojtamolda** [comment]
Fixed in e0e2117b1ed231351a27630621c40c3f551d3d63. I've excluded the `/images/` directory from _npm_ as it makes the package quite large because of the screenshots that are not used in the actual code.

**Comment by mrose17** [comment]
i would not exclude the `images/` directory... if the `readme.md` files references them (and it should!)

**Comment by vojtamolda** [comment]
It's excluded only from the _npm_ package. Do you think someone reads the raw `readme.md` and views the images in the `node_modules/` directory?

I think that people use either _github_ or the [_npm_ package page](https://www.npmjs.com/package/homebridge-ecobee3-sensors) to read the documentation since it's nicely formatted and "clickable" HTML.

**Comment by mrose17** [comment]
in truth, i think that some people do actually that; however, no harm in excluding it and see if you get feedback that confirms my thinking...

**Comment by vojtamolda** [comment]
Okay. Thanks for your feedback. I'm new to the whole _npm_ ecosystem, so I might be easily wrong. I'll be happy to fix it later, but for now I prefer small package over complete documentation. The repo contains 6 MB of images and 15 kB of code.

**Comment by mrose17** [comment]
+1
