### ISSUE TITLE
Convert to Fahrenheit instead of Celsius

### ISSUE THREAD

**Issue by bradleyrawleigh** [vojtamolda/homebridge-ecobee3-sensors#20]
how can i change the read out of this info to F instead of C?

found some references to it in the code but unfamiliar with how to change it to read Fahrenheit stats.

THANKS for any assistance!

**Comment by vojtamolda** [comment]
Hello @bradleyrawleigh,

If you search the settings of your _Ecobee_ you'll find it somewhere over there. Internally all the data exchange happens in C and is converted to F only at the very end for displaying. _Ecobee_ is a Canadian company :smile:

**Comment by bradleyrawleigh** [comment]
Hello @vojtamolda 

Thank You, but unfortunately my ecobee displays all information in F, wether through the iOS App, or the thermostat. Everything is in F, the only thing that shows C, is the devices now visible in the HOME App because of this plugin, i can attach screenshots if that helps any? there are no settings set to C on anything i have with ecobee, even the web portal. though in the code for this plugin i see some code referring to the conversion of F to C. could that information be changed to display F? I also tried changing the device settings in the home app to display F, and I'm given an error regarding permissions, i can attach some of the code in the plugin I'm referring to if that helps? please RE-OPEN this topic as it has not been resolved. Thanks you greatly for your guidance in this.

**Comment by vojtamolda** [comment]
Sorry @bradleyrawleigh, I can't really reopen since this is a problem with your _Ecobee_ or _iOS_ settings and not with this project. I hope you'll understand. I have a limited amount of free time and I can't solve everythig for everyone. Try contacting support. From my own experience I can tell that their answers are pretty quick.

Also make sure you have both the in-app and iOS setting configured correctly like this:
![img_0074](https://user-images.githubusercontent.com/8467740/26957430-a68f3ba6-4c8a-11e7-9993-27bd6bbeb135.PNG)

![img_0075](https://user-images.githubusercontent.com/8467740/26957431-a6a8d160-4c8a-11e7-95b9-8166496cd680.PNG)
